In [1]:
import tensorflow as tf
import numpy as np


2024-09-30 11:38:30.993413: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-30 11:38:31.205238: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-30 11:38:31.283483: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-30 11:38:31.310462: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-30 11:38:31.460895: I tensorflow/core/platform/cpu_feature_guar

In [3]:
import json
with open("graph.json", "r") as f:
    graph = json.load(f)

In [124]:

def get_Mtrx_and_H0(graph):
    H0 = tf.constant(graph['nodes_feature'])
    A = tf.SparseTensor(indices=np.transpose(graph["A"]),
                    values=np.array([v + 0 if index[0] != index[1] else 1
                                     for v, index in zip(graph["edges_feature"], np.transpose(graph["A"]))], dtype=np.float32), 
                    dense_shape=[max(graph["A"][0])+1, max(graph["A"][1])+1])
    d = tf.sparse.reduce_sum(A, axis=1)
    Mtrx = tf.SparseTensor(indices=np.transpose(graph["A"]),
                    values=np.array([v/d[index[0]] for index, v in zip(A.indices, A.values)], dtype=np.float32), 
                    dense_shape=[max(graph["A"][0])+1, max(graph["A"][1])+1])
    
    
    return Mtrx, H0
    

class GraphSegmenter(tf.Module):
    def __init__(self):
        self.W = tf.Variable(tf.random.uniform(shape=[8, 10]))
        self.activation =  tf.nn.relu

    def __call__(self, graph):
        A, H0 = get_Mtrx_and_H0(graph)
        H1 = self.activation(
            tf.matmul(tf.sparse.sparse_dense_matmul(A, H0), self.W)
        )
        
        return tf.reduce_max(H1, axis=1)

def my_loss(H1_emb, H1_true):
    return tf.reduce_sum(tf.pow(H1_emb-H1_true, 2))

In [128]:
Mtrx, H0 = get_Mtrx_and_H0(graph)

In [129]:
model = GraphSegmenter()

In [130]:
model(graph)

<tf.Tensor: shape=(629,), dtype=float32, numpy=
array([ 295.5435 ,  340.61755,  381.22507,  384.31076,  434.5863 ,
        448.38034,  489.10925,  319.31232,  360.4168 ,  407.859  ,
        350.22186,  327.11655,  314.2131 ,  323.82538,  333.02896,
        320.40848,  355.1198 ,  361.4123 ,  367.6586 ,  394.85544,
        389.79208,  386.11075,  425.80878,  450.69257,  442.1421 ,
        429.11203,  547.0942 ,  553.4705 ,  568.5335 ,  355.31287,
        405.58984,  411.17276,  438.97342,  511.27563,  394.35785,
        418.02902,  408.46216,  420.6601 ,  419.42276,  376.04678,
        255.59895,  357.3314 ,  384.34933,  388.60278,  415.7807 ,
        435.06345,  487.95468,  359.3811 ,  413.1594 ,  448.9487 ,
        497.10925,  347.03995,  366.39856,  400.81848,  434.2654 ,
        458.5564 ,  499.77615,  354.83517,  377.08395,  401.27615,
        423.22498,  441.2127 ,  463.62506,  499.3456 ,  365.5009 ,
        389.25684,  411.06934,  430.97327,  434.24515,  443.37152,
        462.71

In [134]:
with tf.GradientTape() as tape:
    h1 = model(graph)
    loss = my_loss(h1, tf.eye(num_rows=629, num_columns=1))

tape.gradient(loss, model.trainable_variables)

(<tf.Tensor: shape=(8, 10), dtype=float32, numpy=
 array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         1.8524386e+11, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         2.9368291e+11, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000

# Вторая модель

In [192]:
with open("claster.json", "r") as f:
    clust = json.load(f)

In [198]:
clus = tf.constant(np.array(clust["clus"]), dtype=tf.dtypes.float32)

In [238]:
class GraphSegmenter2(tf.Module):
    def __init__(self):
        self.W = tf.Variable(tf.random.uniform(shape=[8, 10]))
        self.W2 = tf.Variable(tf.random.uniform(shape=[8, 10]))
        self.activation =  tf.nn.relu

    def __call__(self, graph):
        A, H0 = get_Mtrx_and_H0(graph)
        H1 = self.activation(
            tf.matmul(tf.sparse.sparse_dense_matmul(A, H0), self.W) - tf.matmul(H0, self.W2)
        )
        
        return tf.reduce_max(H1, axis=1)

def my_loss(H1_emb, H1_true):
    return tf.reduce_sum(tf.pow(H1_emb-H1_true, 2))

model2 = GraphSegmenter2()

In [239]:
opt = tf.optimizers.Adam(learning_rate=1.0)
for i in range(50):
    with tf.GradientTape() as tape:
        h1 = model2(graph)
        loss = my_loss(h1, clus)
    
    dW = tape.gradient(loss, model2.trainable_variables)
    opt.apply_gradients(zip(dW, model2.trainable_variables))

In [240]:
with open("graph2.json", "r") as f:
    graph2 = json.load(f)

In [242]:
model2(graph2)

<tf.Tensor: shape=(677,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [237]:
Mtrx, H = get_Mtrx_and_H0(graph)
tf.reduce_max(tf.matmul(tf.sparse.sparse_dense_matmul(Mtrx, H), model2.W), axis=1)

<tf.Tensor: shape=(629,), dtype=float32, numpy=
array([-100.67611 , -121.25881 , -136.58931 , -132.42946 , -154.11803 ,
       -156.46323 , -169.35999 , -110.87806 , -126.728   , -145.87689 ,
       -109.25439 , -111.71451 , -106.963844, -110.732086, -114.31059 ,
       -111.8679  , -123.62674 , -125.728714, -128.24988 , -139.23776 ,
       -136.3829  , -139.3267  , -151.7208  , -161.77507 , -157.51273 ,
       -145.61841 , -188.40791 , -196.52371 , -196.41817 , -111.16015 ,
       -139.03334 , -143.47151 , -154.83267 , -173.30742 , -132.91986 ,
       -144.11055 , -139.51523 , -142.23692 , -134.67084 , -114.85678 ,
        -82.64516 , -104.067604, -117.0756  , -118.7924  , -127.80632 ,
       -137.54512 , -159.18571 , -105.29932 , -124.99538 , -141.45111 ,
       -160.95776 ,  -98.11641 , -105.93004 , -119.19375 , -133.16559 ,
       -143.12733 , -161.76698 ,  -99.501396, -108.48157 , -118.12035 ,
       -126.97947 , -134.3656  , -143.4118  , -160.97939 , -101.91917 ,
       -111.3818

In [220]:
my_loss(model2(graph), clus)

<tf.Tensor: shape=(), dtype=float32, numpy=44371.0>

In [222]:
model2.W

<tf.Variable 'Variable:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.02255897, -0.56373805, -0.23667705, -0.8764673 , -0.0881488 ,
        -0.3762294 ,  0.0786975 , -0.18443012, -0.15318154,  0.04701867],
       [-0.6550233 , -0.2920421 , -0.30421278, -0.16217552, -0.21856076,
        -0.48982003, -0.46877077, -0.45550892, -0.2948032 , -0.4763935 ],
       [ 0.91928804,  0.72769976,  0.8187083 ,  0.13691568,  0.7385869 ,
         0.21124876,  0.08000433,  0.8234364 ,  0.24758875,  0.36636245],
       [ 0.6141236 ,  0.50068104,  0.3811555 ,  0.02555716,  0.45479774,
         0.49741292,  0.37239134,  0.04489887,  0.87694824,  0.19765425],
       [ 0.21644545,  0.3949932 ,  0.5916754 ,  0.8857025 ,  0.18231559,
         0.06700742,  0.02315974,  0.931944  ,  0.49277127,  0.37972426],
       [ 0.72347534,  0.91455245,  0.81568813,  0.68924546,  0.23569977,
         0.6623441 ,  0.11481607,  0.41421223,  0.75635934,  0.8727002 ],
       [ 0.47485054,  0.2408818 ,  0.1656326 ,  0.583086